# basic options
title: hack.mod.code.build
author: Osmo
email: osmo@sdf.org
description: hack.mod.code.build
twitter_username: osmo
github_username:  osmo

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
