# basic options
title: Osmo
author: Osmo
email: osmo@sdf.org
description: hack.mod.code.build
twitter_username: osmo
github_username:  osmo

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
google_analytics: UA-111281484-1
